=head1 Was ist dies?

If you use the L<MacLoggerDX|http://www.dogparksoftware.com/MacLoggerDX.html>
L<HAM radio|https://en.wikipedia.org/wiki/Amateur_radio> logging software and
know how to run a L<perl|https://www.perl.org/about.html> script, this stuff might be of interest/useful to you.

=head1 Configuration

See the C<sample-config.yml> file in the repo for all availble configuration
options.  All of the scripts look for this file as C<config.yml> in the current directory.

=head2 send-qsls.pl

This script uploads QSL entries with empty QSL Sent columns to
L<LoTW|https://lotw.arrl.org/>, L<eQSL|http://eqsl.com> and
L<QRZ.com|http://www.qrz.com>.

=head2 fix-confirmations.pl

If you use DQSL manager to import eQSL & LoTW confirmations into MacLoggerDX you
can somtetimes end up with duplicates in the QSL Received column of the log such as
C<eQSL.cc:Y, LoTW:20150917, LoTW:20150919>.  This script keeps just the first
confirmation entry for each type.

=head2 udp-tune.pl

 Listens to MacLoggerDX UDP broadcast for DX cluster spots and tunes Fldigi to
 desired frequency and sets modem.
