---
QRZ_LOGBOOK_KEY: ABC-123-QRZ-123B7-E85B-8481-88D3
EQSL_USER:       AC2RK
EQSL_PWD:        stansmom123
DB:              /Users/you/Documents/MLDX_Logs/MacLoggerDX.sql
lotw_path:       /Applications/tqsl.app/Contents/MacOS/tqsl
lotw_site:       Home
lotw_call:       AC2RK
